title: Webfusion Solutions
description: AI, Automation, and Digital Services such as Web Design, Social Media, and Marketing
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: webfusion
github_username: webfusion

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  services:
    output: true
  products:
    output: true
